sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - compiler: gcc
      env:
        - USING_GCC=true
    - compiler: clang
      env:

before_install:
 - sudo apt-get update -qq
 - wget https://github.com/psavery/qwt/releases/download/6.1.3-2.deb/qwt_6.1.3-2.deb

install:
 - sudo apt-get install -qq qt5-default libeigen3-dev libssh-dev
                            libqt5svg5 lcov
 - sudo dpkg -i qwt_6.1.3-2.deb

before_script:
 # We have to load the travis-ci display to run the tests even though
 # we don't actually need the display...
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3 # give xvfb some time to start

 - export CMAKE_FLAGS="$CMAKE_FLAGS -DBUILD_INDEPENDENT_PACKAGE=ON"
 - export CMAKE_FLAGS="$CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=install/xtalopt"
 - export CMAKE_FLAGS="$CMAKE_FLAGS -DBUILD_TESTS=ON"
 - mkdir build
 - cd build
 - mkdir install
 - cmake ${CMAKE_FLAGS} ..

script:
 - make -j2 install
 - ctest --output-on-failure

after_success:
 # For GCC only: capture coverage info, filter out system, print debug info,
 # and upload to codecov
 - if [[ "$USING_GCC" == "true" ]]; then
     lcov --directory . --capture --output-file coverage.info &&
     lcov --remove coverage.info '/usr/*' --output-file coverage.info &&
     lcov --list coverage.info &&
     bash <(curl -s https://codecov.io/bash) ||
     echo "Codecov did not collect coverage reports";
   fi

 # If this is a tag, then zip the install directory, md5sum it, and upload it
 - if [[ -n "$TRAVIS_TAG" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
     echo "Tag detected. Zipping installation and creating md5sum." &&
     cd install &&
     tar -czvf linux-xtalopt.tgz xtalopt &&
     md5sum linux-xtalopt.tgz > linux-xtalopt.md5;
   else
     echo "Tag not detected. Skipping zip and md5sum.";
   fi

deploy:
  provider: releases
  file:
    - linux-xtalopt.tgz
    - linux-xtalopt.md5
  skip_cleanup: true
  api_key:
    secure: OV+fiXKG9XW6AHN2p79aFdIiGbkf6ofatJ0QWLzOhtAylrUmKL2rdaQLve64g7DXdzDMuUKXLncXPYdIoPLYau9CvZvejNhGCKH+GDRuUuW1TbivRHEBQvxZCGqH5YGKTRLu8Ip7RNeQo0+3KWT6aed971NVzPV2zgET1okSvDFTJIC+ZyZ6gd2u0WeKPerVgZk9RgF7liIykJnL74mi51IRDslKNNsyXC2fEDwRqCBpO6E2QpxSHnTKmMLy1jdfI+V1bEyqi3Bfc8lRuzbUh5YpxZ0GQlzjWqLosAaIVy07YON3UcPQz6aiXr0PGUXknVLwK2y2Vdo2LV3KGo9o5ahyU2roXThVCyhVRPyYKU+4PdXJPeH3dmOmc25keF9ubWhgvWCExacue7g1ww4cN+yKHAJJOlsHyIaDhS/F72nKad4YVSpLpw0pY29qY8yrEHGYW2YbIP70UL2r70KIBFvsaBBbIrl0N5CnRsmbZkGi0urXgYttfw/ehhgPkDgueONjnGHgqbPSHQ0JpxlOWSy8ghjhYpXTDVaUp54uWZfN7OnqufN5rkCoWA5Q6Qkh8PbiOPNb9IMuzkP1wlxYtVI43vUekeS7+RVtXnowrKb1z/19kCeZrvKuVM18achHwM6uXMbn6IjQLHJqpn21n8tca+6gyWDZGiuYzkceHhQ=
  on:
    repo: xtalopt/XtalOpt
    tags: true
    all_branches: true
